-- MySQL Script generated by MySQL Workbench
-- 09/26/18 21:43:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_avc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_avc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_avc` DEFAULT CHARACTER SET utf8 ;
USE `bd_avc` ;

-- -----------------------------------------------------
-- Table `bd_avc`.`jogadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_avc`.`jogadores` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'indetificação da tabela jogadores',
  `nome` VARCHAR(45) NOT NULL COMMENT 'nome dos jogadores',
  `sobrenome` VARCHAR(45) NOT NULL COMMENT 'sobrenome dos jogadores',
  `usuario` VARCHAR(18) NOT NULL COMMENT 'nome de usuario dos jogadores',
  `avatar` VARCHAR(45) NOT NULL COMMENT 'atributo onde será guardado o nome da imagem do avatar do jogador',
  `data_cadastro` DATETIME NOT NULL COMMENT 'data do cadastro do jogador',
  `email` VARCHAR(45) NOT NULL COMMENT 'email do jogador',
  `senha` VARCHAR(60) NOT NULL COMMENT 'senha do jogador',
  `data_nasci` DATE NOT NULL COMMENT 'data de nascimento do jogador',
  `nivel_prova` TINYINT(1) NOT NULL,
  `nmr_prova` TINYINT(1) NOT NULL,
  `pontuacao` DECIMAL(4,2) NOT NULL,
  `provas_feitas` INT(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabela dos jogadores';


-- -----------------------------------------------------
-- Table `bd_avc`.`niveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_avc`.`niveis` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'identificação dos níveis',
  `nome` VARCHAR(45) NOT NULL COMMENT 'nome dos níveis',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabela de níveis';


-- -----------------------------------------------------
-- Table `bd_avc`.`temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_avc`.`temas` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'identificação do tema',
  `nome` VARCHAR(45) NOT NULL COMMENT 'nome do tema',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabela onde conterá os temas das provas ';


-- -----------------------------------------------------
-- Table `bd_avc`.`provas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_avc`.`provas` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'identicação das provas',
  `temas_id` INT(10) UNSIGNED NOT NULL COMMENT 'atributo identificador da tabela temas',
  `niveis_id` INT(10) UNSIGNED NOT NULL COMMENT 'atributo identificador da tabela níveis',
  `nome` VARCHAR(45) NOT NULL COMMENT 'nome das provas ',
  `gato_prova` INT(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_provas_temas1_idx` (`temas_id` ASC),
  INDEX `fk_provas_niveis1_idx` (`niveis_id` ASC),
  CONSTRAINT `fk_provas_niveis1`
    FOREIGN KEY (`niveis_id`)
    REFERENCES `bd_avc`.`niveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_provas_temas1`
    FOREIGN KEY (`temas_id`)
    REFERENCES `bd_avc`.`temas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabela de provas';


-- -----------------------------------------------------
-- Table `bd_avc`.`questoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_avc`.`questoes` (
  `enunciado` VARCHAR(200) NOT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'identificação dos níveis',
  `alternativa_a` VARCHAR(200) NOT NULL COMMENT 'questão A',
  `alternativa_b` VARCHAR(200) NOT NULL COMMENT 'questão B',
  `alternativa_c` VARCHAR(200) NOT NULL COMMENT 'questão C',
  `alternativa_d` VARCHAR(200) NOT NULL COMMENT 'questão D',
  `correta` VARCHAR(200) NOT NULL COMMENT 'atributo que guardará a questão correta',
  `peso` INT(11) NOT NULL COMMENT 'atributo onde vamos definir o valor que valerá as questões',
  `provas_id` INT(10) UNSIGNED NOT NULL COMMENT 'atributo identificador da tabela provas',
  PRIMARY KEY (`id`),
  INDEX `fk_questoes_provas1_idx` (`provas_id` ASC),
  CONSTRAINT `fk_questoes_provas1`
    FOREIGN KEY (`provas_id`)
    REFERENCES `bd_avc`.`provas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabela das questões';


-- -----------------------------------------------------
-- Table `bd_avc`.`jogadores_has_questoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_avc`.`jogadores_has_questoes` (
  `jogadores_id` INT(10) UNSIGNED NOT NULL COMMENT 'atributo identificador da tabela jogadores',
  `questoes_id` INT(10) UNSIGNED NOT NULL COMMENT 'atributo identificador da tabela questões',
  `resposta` VARCHAR(45) NOT NULL COMMENT 'atributo onde guardará a resposta selecionada pelos jogadores',
  PRIMARY KEY (`jogadores_id`, `questoes_id`),
  INDEX `fk_jogadores_has_questoes_questoes1_idx` (`questoes_id` ASC),
  INDEX `fk_jogadores_has_questoes_jogadores_idx` (`jogadores_id` ASC),
  CONSTRAINT `fk_jogadores_has_questoes_jogadores`
    FOREIGN KEY (`jogadores_id`)
    REFERENCES `bd_avc`.`jogadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogadores_has_questoes_questoes1`
    FOREIGN KEY (`questoes_id`)
    REFERENCES `bd_avc`.`questoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabela associatiova de jogadores e questões';


-- -----------------------------------------------------
-- Table `bd_avc`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_avc`.`logs` (
  `id` INT(10) UNSIGNED ZEROFILL NOT NULL COMMENT 'identificação da tabela logs',
  `data` DATETIME NOT NULL COMMENT 'data dos logins dos jogadores',
  `jogadores_id` INT(10) UNSIGNED NOT NULL COMMENT 'atributo identificador da tabela jogadores',
  PRIMARY KEY (`id`),
  INDEX `fk_logs_jogadores1_idx` (`jogadores_id` ASC),
  CONSTRAINT `fk_logs_jogadores1`
    FOREIGN KEY (`jogadores_id`)
    REFERENCES `bd_avc`.`jogadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabela de logins';


-- -----------------------------------------------------
-- Table `bd_avc`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_avc`.`professores` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'identificação da tabela professores',
  `nome` VARCHAR(45) NOT NULL COMMENT 'nome dos professores',
  `sobrenome` VARCHAR(45) NOT NULL COMMENT 'sobrenome dos professores',
  `usuario` VARCHAR(45) NOT NULL COMMENT 'nome de usuário dos professores',
  `email` VARCHAR(45) NOT NULL COMMENT 'email dos professores',
  `senha` VARCHAR(60) NOT NULL COMMENT 'senha dos professores',
  `data_cadastro` DATETIME NOT NULL COMMENT 'data do cadastro dos professores',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabela dos professores';


-- -----------------------------------------------------
-- Table `bd_avc`.`provas_cadastradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_avc`.`provas_cadastradas` (
  `id` INT NOT NULL,
  `nome` VARCHAR(2000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_avc`.`questoes_cadastradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_avc`.`questoes_cadastradas` (
  `id` INT NOT NULL,
  `enunciado` VARCHAR(2000) NOT NULL,
  `alternativa_a` VARCHAR(200) NOT NULL,
  `alternativa_b` VARCHAR(200) NOT NULL,
  `alternativa_c` VARCHAR(200) NOT NULL,
  `alternativa_d` VARCHAR(200) NOT NULL,
  `correta` CHAR(1) NOT NULL,
  `peso` DECIMAL(4,2) NOT NULL,
  `provas_cadastradas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questoes_cadastradas_provas_cadastradas1_idx` (`provas_cadastradas_id` ASC),
  CONSTRAINT `fk_questoes_cadastradas_provas_cadastradas1`
    FOREIGN KEY (`provas_cadastradas_id`)
    REFERENCES `bd_avc`.`provas_cadastradas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
